# fly.toml app configuration file generated for quiet-water-5040 on 2023-09-25T09:37:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quiet-water-5040"
primary_region = "scl"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
